name: Deploy Portfolio To VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd ~/gitproject/Portfolio
          git pull origin main
          docker build -t portfolio .
          docker stop portfolio-container || true
          docker rm portfolio-container || true
          docker run -d --name portfolio-container -p 3000:3000 portfolio
